# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mathew Rogers"
resume_title:                   "Data Scientist and Mathematician"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mathewrogers@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

  #resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a data scientist in Montreal. Over the last few years, I have worked in machine learning, streaming data, data science, and computer vision. My experience also includes a significant amount of software engineering. My PhD is in number theory with a focus on conjectures relating to elliptic curves. Feel free to reach out, I'm always looking for a challenge.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/matrogersmtl"
  resume_twitter_url:           "http://twitter.com/matrogersmtl"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/rogersmontreal"
  resume_scholar_url:           "https://scholar.google.ca/citations?user=cnec4HkAAAAJ&hl=fr"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://matrogersmtl.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
